### ISSUE TITLE
Is is possible to deactivate Orchestrator persistence?

### ISSUE THREAD

**Issue by aisensiy** [bitpoke/mysql-operator#610]
https://github.com/presslabs/mysql-operator/blob/dfdea2b24bbd3981bbbbca56ee4f529e00430db9/charts/mysql-operator/values.yaml#L117

What will happen if I set this `false` after restart the operator? Does this make the whole mysql cluster unavailable to use?

**Comment by Rahulsharma0810** [comment]
```
-rw-r--r-- 1 777 65533 644K Sep 29 23:28 orc.db
-rw-r--r-- 1 777 65533  32K Sep 29 23:28 orc.db-shm
-rw-r--r-- 1 777 65533 4.0M Sep 29 23:28 orc.db-wal
-rw-r--r-- 1 777 65533  16K Sep 29 23:28 raft_store.db
drwxr-xr-x 2 777 65533 4.0K Sep 29 23:22 snapshots
```
this have orchestrator data, after the restart, you will lose it and cluster state.

**Comment by AMecea** [comment]
Hi @aisensiy, @Rahulsharma0810 is right. That data will be lost at every operator restart but the operator should work because the soure of truth is in k8s. The main problem is that the operator is not tested in this case very well.

May I know what dosn't work and why you need to deactivate Orchestrator persistance?
Thank you!

**Comment by aisensiy** [comment]
I just want to minimize the persistence volume dependency. For example if the kubernetes cluster persistence volumes are broken, how can I recoverty the whole operator? The mysql pvc will have s3 backup to recovery, while the Orchestrator have no backup? 

It seems that the Orchestrator persistence is just unnecessary?

**Comment by nick4fake** [comment]
Why is this completed? There is nothing in README that describes this
