### ISSUE TITLE
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+

### ISSUE THREAD

**Issue by w33dw0r7d** [bitpoke/mysql-operator#846]
`warning_handler.go:65] KubeAPIWarningLogger "msg"="policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget"`

I think need fix deprecated api versions. And remove PSP. 
I can make PR.
@cndoit18

**Comment by kudiyarov** [comment]
Mysql-operator is unable to start on 1.25 k8s due to watching already removed "policy/v1beta1" version - [mysqlcluster_controller.go](https://github.com/bitpoke/mysql-operator/blob/v0.6.2/pkg/controller/mysqlcluster/mysqlcluster_controller.go#L107)
Operator's log message:
`E0914 13:55:00.560358       1 deleg.go:144] mysql-operator "msg"="unable to start the manager" "error"="failed to wait for controller.mysqlcluster caches to sync: no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""`

Please move to v1 before 0.6.3 release
